/* 预加载 */
var manifest = [
  { src:'./images/load.png'},
  { src:'./images/logo.png'},
  { src:'./images/music.png'},
  { src:'./1.mp4'},

  { src:'./images/bg.png'},
  { src:'./images/bg2.png'},
  { src:'./images/btn-prize.png'},
  { src:'./images/btn-rule.png'},
  { src:'./images/btn-start1.png'},
  { src:'./images/btn-start2.png'},
  { src:'./images/btn-start3.png'},
  { src:'./images/btn-start4.png'},
  { src:'./images/main.png'},
  { src:'./images/tips.png'},
  { src:'./images/share/1.png'},
  { src:'./images/share/2.png'},
  { src:'./images/share/3.png'},
  { src:'./images/share/4.png'},
  { src:'./images/share/5.png'},
  { src:'./images/share/6.png'},
  { src:'./images/share/7.png'},
  { src:'./images/share/8.png'},
  { src:'./images/center/1.png'},
  { src:'./images/center/2.png'},
  { src:'./images/center/3.png'},
  { src:'./images/center/4.png'},
  { src:'./images/center/5.png'},
  { src:'./images/alert/btn-login.png'},
  { src:'./images/alert/empty.png'},
  { src:'./images/alert/get-prize.png'},
  { src:'./images/alert/infor.png'},
  { src:'./images/alert/login.png'},
  { src:'./images/alert/my-prize.png'},
  { src:'./images/alert/red-bag.png'},
  { src:'./images/alert/rule.png'},
  { src:'./images/alert/tips.png'},
  { src:'./images/alert/share.png'}
  
]