/* 预加载 */
var manifest = [
  { src:'./images/logo.png'},
  { src:'./images/music.png'},

  { src:'./images/load/bg.jpg'},
  { src:'./images/load/head.png'},
  { src:'./images/load/img.png'},
  { src:'./images/load/progress-bg.png'},
  { src:'./images/load/progress-color.png'},
  { src:'./images/load/progress-point.png'},

  { src:'./images/alert/from-tel.png'},
  { src:'./images/alert/from-tips.png'},
  { src:'./images/alert/from-user.png'},
  { src:'./images/alert/line.png'},
  { src:'./images/alert/login.png'},
  { src:'./images/alert/point-tip.png'},
  { src:'./images/alert/point-tip2.png'},
  { src:'./images/alert/prize-bg.png'},
  { src:'./images/alert/prize-bg-img.png'},
  { src:'./images/alert/prize-empty.png'},
  { src:'./images/alert/prize-empty2.png'},
  { src:'./images/alert/rule.png'},
  { src:'./images/alert/score.png'},
  { src:'./images/alert/tip.png'},
  { src:'./images/alert/txt-your-prize.png'},
  { src:'./images/alert/txt-your-score.png'},
  { src:'./images/alert/warn-bg.png'},
  { src:'./images/alert/warn-txt.png'},

  { src:'./images/btn/btn-alert-again.png'},
  { src:'./images/btn/btn-alert-false.png'},
  { src:'./images/btn/btn-alert-login.png'},
  { src:'./images/btn/btn-alert-submit.png'},
  { src:'./images/btn/btn-alert-true.png'},
  { src:'./images/btn/btn-i-know.png'},
  { src:'./images/btn/btn-my-prize.png'},
  { src:'./images/btn/btn-rule.png'},
  { src:'./images/btn/btn-share.png'},
  { src:'./images/btn/btn-start.png'},

  { src:'./images/game/bg.png'},
  { src:'./images/game/head.png'},
  { src:'./images/game/house.png'},
  { src:'./images/game/leftTime/bg.png'},
  { src:'./images/game/leftTime/left-time.png'},
  { src:'./images/game/leftTime/line.png'},
  { src:'./images/game/leftTime/m.png'},
  { src:'./images/game/leftTime/s.png'},

  { src:'./images/index/img.png'},
  { src:'./images/index/snow1.png'},
  { src:'./images/index/snow2.png'},

  { src:'./images/share/bg.jpg'},
  { src:'./images/share/txt.png'},

  { src:'./images/snow.png'}
]